# Build geowars

name: CMake build geowars matrix

on:
  push:
    branches:
      - dev
      - main
env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.config.name }}
    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Windows VS2019, os: windows-2019 }
          - { name: Windows VS2022, os: windows-2022 }
          - { name: Windows-Latest, os: windows-latest }
          - { name: Linux GCC,      os: ubuntu-latest }
          - { name: Linux Clang,    os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
          - { name: macOS,          os: macos-latest }
        config:
          - { name: Shared, flags: -DBUILD_SHARED_LIBS=TRUE }
          - { name: Static, flags: -DBUILD_SHARED_LIBS=FALSE }

    steps:
      - name: Install linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -B test_build ${{matrix.platform.flags}} ${{matrix.config.flags}}

      - name: Build
        run: cmake --build test_build --config Release




